### ISSUE TITLE
IE11 - Error: SCRIPT5005: String expected

### ISSUE THREAD

**Issue by florinrelea** [vue-stripe/vue-stripe#109]
**Describe the bug**
IE11 returns this error: SCRIPT5005: String expected, index.js (439,5)
Version: "^3.0.0-beta.11"
I tried to transpile 'vue-stripe-checkout' but the error is the same.

**To Reproduce**
1. Start a local server
2. Open Internet Explorer
3. Open the console

**Screenshots**
![Untitle3d](https://user-images.githubusercontent.com/56991338/81034058-8b398100-8e9e-11ea-8905-a5019c3b2213.png)
![Un2titled](https://user-images.githubusercontent.com/56991338/81034059-8c6aae00-8e9e-11ea-836f-be22337b8942.png)

**Additional context**
My screenshots are made after using try{}catch(){} in "node_modules\vue-stripe-checkout\dist\index.js".
The default error is : SCRIPT5005: String expected, index.js (439,5)

**Comment by jofftiquez** [comment]
Hello @florinrelea thank you for posting this. Have you tried the latest version `v3.3.1`? For full disclosure this plugin hasn't been tested in any IE browsers yet.

**Comment by florinrelea** [comment]
Hi! Just tried to run my app using "vue-stripe-checkout": "^3.3.1". Same error.

**Comment by jofftiquez** [comment]
> Hi! Just tried to run my app using "vue-stripe-checkout": "^3.3.1". Same error.

Hello @florinrelea `vue-stripe-checkout` was the old version. Could you use `@vue-stripe/vue-stripe`? Thanks.
