### ISSUE TITLE
Typescript definition outdated

### ISSUE THREAD

**Issue by WoLpH** [vue-stripe/vue-stripe#110]
**Describe the bug**

The typescript definition currently defines a single interface instead of the separate `StripeCheckout` and `StripeElements` definition.

**Expected behavior**

A typescript definition somewhere along these lines:
```typescript
declare module 'vue-stripe-checkout';
{
    export class StripeCheckout { ... }
    export class StripeElements { ... }
}
```

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser Chrome
 - Version 81

**Additional context**

**Comment by WoLpH** [comment]
I'm far from a typescript expert, but I believe something like this might work:
```typescript
import Vue from 'vue';

declare module 'vue-stripe-checkout' {
    export class StripeCheckout extends Vue {
        pk: String;
        items: [];
        successUrl: String;
        cancelUrl: String;
        submitType: String;
        billingAddressCollection: String;
        clientReferenceId: String;
        customerEmail: String;
        sessionId: String;
        locale: String;
    }

    export class StripeElements extends Vue {
        pk: String;
        amount: Number;
        stripeAccount: String;
        apiVersion: String;
        locale: String;
    }
}
```

**Comment by jofftiquez** [comment]
Hello @WoLpH my apologies, I am not a typescript expert myself. If could help me verify your code suggestion, I'd be happy to accept a PR from you so we can update this. Thank you so much.

**Comment by WoLpH** [comment]
I can't say I really know how to add automatic tests to a javascript library with typescript definitions... When importing the library from a typescript project the typescript converter automatically gives you warnings if anything is broken.

Within this project however... I wouldn't know where to start. With a few hints from `tsd` I got to this diff:
```diff
diff --git a/package.json b/package.json
index fbeb284..5c79166 100644
--- a/package.json
+++ b/package.json
@@ -51,6 +51,7 @@
   "bugs": {
     "url": "https://github.com/jofftiquez/vue-stripe-checkout/issues"
   },
+  "types": "types",
   "homepage": "https://github.com/jofftiquez/vue-stripe-checkout#readme",
   "dependencies": {
     "package-lock-only": "0.0.4"
diff --git a/types/index.d.ts b/types/index.d.ts
new file mode 100644
index 0000000..af31787
--- /dev/null
+++ b/types/index.d.ts
@@ -0,0 +1,28 @@
+import Vue from 'vue';
+
+declare module 'vue-stripe-checkout' {
+    export class StripeCheckout extends Vue {
+        pk: String;
+        items: [];
+        successUrl: String;
+        cancelUrl: String;
+        submitType: String;
+        billingAddressCollection: String;
+        clientReferenceId: String;
+        customerEmail: String;
+        sessionId: String;
+        locale: String;
+
+        redirectToCheckout(): void;
+    }
+
+    export class StripeElements extends Vue {
+        pk: String;
+        amount: Number;
+        stripeAccount: String;
+        apiVersion: String;
+        locale: String;
+
+        submit(): HTMLElement;
+    }
+}
diff --git a/types/index.test-d.ts b/types/index.test-d.ts
new file mode 100644
index 0000000..803e85d
--- /dev/null
+++ b/types/index.test-d.ts
@@ -0,0 +1 @@
+import {StripeCheckout, StripeElements} from 'vue-stripe-checkout';
diff --git a/typings/index.d.ts b/typings/index.d.ts
deleted file mode 100644
index eca513b..0000000
--- a/typings/index.d.ts
+++ /dev/null
@@ -1,5 +0,0 @@
-export interface _VueStripeCheckout {
-  install: (Vue: any, options?: any) => void
-}
-export declare const VueStripeCheckout: _VueStripeCheckout;
-export default VueStripeCheckout;
```

Which results in this output:
```
# tsd

  types\index.d.ts:1:16
  ✖   1:16  Cannot find module vue or its corresponding type declarations.
  ✖  26:18  Cannot find name HTMLElement.

  types\index.test-d.ts:1:45
  ✖   1:45  Cannot find module vue-stripe-checkout or its corresponding type declarations.

  3 errors
```

So something else is probably needed. Perhaps a `tsconfig.json` file but I'm honestly not sure.

**Comment by jofftiquez** [comment]
Alright, thanks for the information @WoLpH I'll try to give time to look this up. :)

**Comment by Deph0** [comment]
Bump on this, would be nice to have as it's a big requirement for using typescripted Vue components (projects can be created using vue cli).
I used the typedefs WoLpH provided (kudos), but of course would rather not have to make my own.

For those as confused as i was, create a folder called types, and inside a file named index.d.ts, copypaste WoLpH's type definitions, update tsconfig.json, add this into 'compilerOptions'
```json
   "typeRoots": [
      "./node_modules/@types",
      "./src/types/",
    ],
```

**Comment by 9AZX** [comment]
Hey, i have the same problem and i don't know how to deal with it. The @Deph0's solution doesn't work for me.

**Comment by equinoxmatt** [comment]
Can confirm, I also cannot get @Deph0 solution to work. This is a big issue.

**Comment by saniales** [comment]
I opened a PR, can you please double check? thank you <3

**Comment by jofftiquez** [comment]
Hello @saniales thanks, on it.

Everyone, I apologize for this issue, I am not really that familiar with typescript typings yet, and I was really busy at work. I really appreciate your comments, I am also learning in the process. Thanks for the help.

**Comment by jofftiquez** [comment]
Hello all kindly check `v4.1.5`

**Comment by equinoxmatt** [comment]
@saniales - really appreciate the PR and @jofftiquez for getting this merged in so quickly.  I got the workaround working, but this is so much nicer!

**Comment by saniales** [comment]
Thank you people, happy to help more in the future <3
