### ISSUE TITLE
[Documentation] Examples of how to a custom form with Stripe elements

### ISSUE THREAD

**Issue by Ahmedie-m** [vue-stripe/vue-stripe#113]
Please document simple examples of how to a custom form with Stripe elements, I have not had any luck with adding basic text-fields for name and surnames, etc.

Thank you very much.

**Comment by sdwru** [comment]
Yes, this seems to be a shortcoming of this project at the moment.  The examples posted in the readme do not give you what is show in the screenshot at the top of the page.  The examples only give you a little button.  I was scratching my head for awhile before I finally figured out that the examples are not the same thing as the screenshot.  So it's pretty confusing the way the readme is written.

**Comment by Ahmedie-m** [comment]
@sdwru Have you perhaps figured it out? We can help and PR this readme and make value to other users.

**Comment by jofftiquez** [comment]
@sdwru 
> The examples posted in the readme do not give you what is show in the screenshot at the top of the page. 

The screenshot shown on the documentation is a screenshot of the `Checkout` component, not the `Elements` component.

If you guys want to mount a custom field, the `Elements` component actually has a `slot` for this. It's called `card-element`. See [here](https://github.com/jofftiquez/vue-stripe-checkout/blob/11da3650e1758974809b9cb186007106523bbd73/src/Elements.vue#L4).

@sdwru 
> The readme only provides links to stripe which only gives very generic guidance. There should be a more concrete vue implementation example that results in the stripe checkout form that is show in the screenshot at the top of the readme.

The readme provides an example of how to use the component, the properties are documented on Stripe's website, all of checkout's checkout parameters are properly mirrored in this project as properties. This should be enough if you know how to use a basic vue component.

If you want to improve the README, feel free to do a PR. Thank you.

**Comment by jofftiquez** [comment]
Hello. A new documentation including the new vue stripe elements is on the way.

**Comment by jofftiquez** [comment]
Hello kindly refer to the following fresh docs 😄 

- [Getting started with Elements](https://vuestripe.com/stripe-elements/getting-started)
- [Using the Card component](https://vuestripe.com/stripe-elements/card)
- [Get full access to Stripe SDK through Elements Plugin](https://vuestripe.com/stripe-elements/plugin)
