### ISSUE TITLE
How to implement stripe strong customer authentication

### ISSUE THREAD

**Issue by caeser1996** [vue-stripe/vue-stripe#116]
How to implement stripe strong customer authentication I am unable to see any option in plugin please provide if you have any reference. Your kind consideration is required.

Regards,
Sumanta Mukhopadhyay

**Comment by MohawkMan** [comment]
I'm not in production yet but I have this is working in test:

`
    confirmCardPayment (clientSecret) {
      const stripe = this.$refs.elementsRef.stripe
      const card = this.$refs.elementsRef.card
      if (clientSecret && stripe && card) {
        stripe.confirmCardPayment(clientSecret, {
          payment_method: {
            card: card
          }
        })
          .then(r => {
            console.log(r)
            if (r.error) {
              // Show error to your customer (e.g., insufficient funds)
              console.log(result.error.message);
            } else {
              if (r.paymentIntent.status === 'succeeded') {
                 // Show a success message to your customer
                 // There's a risk of the customer closing the window before callback
                 // execution. Set up a webhook or plugin to listen for the
                 // payment_intent.succeeded event that handles any business critical
                 // post-payment actions.
              }
            }
          })
      }

`

**Comment by jofftiquez** [comment]
Hello thanks for this issue. Could you be more elaborate? Are you referring to Stripe Checkout, or the Stripe Elements? For checkout, I believe this is working out of the box already if your card requires 2FA? Correct me if I'm wrong. 

For Stripe Elements, I haven't done my research about this yet. I saw @MohawkMan's example, would kindly send me the documentation link of this? I'll be glad to incorporate this. Thanks :)

**Comment by MohawkMan** [comment]
@jofftiquez it works for both. If you are using elements you have to set up a payment intent (usually server side) which will return a client secret and then call confirmCardPayment with the secret and the card element. So if you just had a method that you can pass the client secret and a callback that would call confirmCardPayment then it would just be slightly cleaner than using the $refs to get to it.

**Comment by jofftiquez** [comment]
@MohawkMan I see, thank you for this. I will find time to implement it. Thank you so much!

**Comment by jofftiquez** [comment]
Hello @caeser1996 @MohawkMan in the latest version, if you are using the `StripeElementCard` component you will be able to access the `stripe` instance, `elements` instance, and the `element` object via `$ref`. I assigned them to local state data [see here](https://github.com/vue-stripe/vue-stripe/blob/6f1ab0b935590aec24fa388378caa0fc9829f336/src/elements/Card.vue#L89-L91). Thus, you can call the `confirmCardPayment` method like so:

```javascript
this.$refs.cardElementRef.element.confirmCardPayment(clientSecret, data?, options?);
```

I guess, I need to create more examples for instances like these. I will be closing this for now. Thank you for your patience.

**Comment by drummerroma** [comment]
@MohawkMan 
For who needs a working sample this should now work like this:

```
confirmCardPayment(clientSecret) {
    const stripe = this.$refs.elementRef.stripe
    const card = this.$refs.elementRef.element
    if (clientSecret && stripe && card) {
        stripe.confirmCardPayment(clientSecret, {
            payment_method: {
                card: card
            }
        })
            .then(r => {
                console.log(r);
            if (r.error) {
                // Show error to your customer (e.g., insufficient funds)
                console.log(r.error.message);
            } else {
                if (r.paymentIntent.status === "succeeded") {
                // Show a success message to your customer
                // There's a risk of the customer closing the window before callback
                // execution. Set up a webhook or plugin to listen for the
                // payment_intent.succeeded event that handles any business critical
                // post-payment actions.
        }
    }
});
```
