### ISSUE TITLE
Can I create stripe-elements and autofill card?

### ISSUE THREAD

**Issue by Rouzy777** [vue-stripe/vue-stripe#144]
I'm building auto filling system in my checkout page and want to add feature when card number is autofilling in stripe-elements input.

What's the best way to do this?

**Comment by jofftiquez** [comment]
Hello @Rouzy777 I am currently re-checking the elements documentation. A major update is on the way, I don't yet if there's a way to do that autofilling that you mentioned, but I will keep you updated here. Thanks.

**Comment by jofftiquez** [comment]
Hello @Rouzy777 using the latest version you can follow [this guide](https://vuestripe.com/stripe-elements/plugin), then you can prefill the field using the element id. Closing this for now. Thanks.
