### ISSUE TITLE
SKU depricated by stripe ?

### ISSUE THREAD

**Issue by robov** [vue-stripe/vue-stripe#145]
When I follow your example I need to specify the sku, But there is no way that I see a sku in my product or price.

Stripe Docs:
A: Plans and SKUs were old ways to model recurring and one-off prices. We created the Prices API to unify the two concepts and make it easier to reason about your pricing catalog. You can still pass old Plan and SKU IDs to Checkout -- to learn more read our docs but know that you do not need to migrate any of your existing SKUs and Plans.

So it seems that the skus are outdated.
How can I get your package to work again ?

**Comment by mits87** [comment]
The same for me 👀

**Comment by jofftiquez** [comment]
Hello @robov the current documentation is outdated, a new one is on the way tho. May I ask what exactly is your use case? How do you plan to make the payment checkout flow work on client side? Thanks.

**Comment by marctaule** [comment]
same for me. I can't find sku in stripe dashboard :(

**Comment by saifamp** [comment]
are skus and products the same thing?

**Comment by JeffJassky** [comment]
Solution:

Here's how you can use a Price ID instead of a SKU: https://github.com/jofftiquez/vue-stripe-checkout/issues/132#issuecomment-688435860

**Comment by jofftiquez** [comment]
Hello the new docs now shows `lineItems` on the examples. Closing this now. Thank you.
