### ISSUE TITLE
TypeError: this.$refs.checkoutRef.redirectToCheckout is not a function

### ISSUE THREAD

**Issue by cmedinadeveloper** [vue-stripe/vue-stripe#154]
Hi! I am trying to implement this library on a Quasar + Typescript project, everything is fine until I press the button to go to the Checkout page because within the $ref's object there is no method called "redirectToCheckout".

![image](https://user-images.githubusercontent.com/33674559/102948328-2322c400-449c-11eb-8014-0f89e2275f05.png)

Hope you can help! Thanks!

**Comment by jofftiquez** [comment]
Hello @cmedinadeveloper would mind sending the snippet of your code as well? Thanks.

**Comment by cmedinadeveloper** [comment]
```
<template>
  <MainContainer
    :showHeaderBack="true"
    :showHeader="true"
    :headerBlue="true"
    class="containerSucces"
    :headerTitle="$tc('SEND_STRIPE.HEADER_TILE')"
    :toolbarColor="'toolbarBlue'"
  >
    <div slot="page-container" class="q-mt-lg">
      <StripeCheckout
        ref="checkoutRef"
        :pk="publishableKey"
        :successUrl="successUrl"
        :cancelUrl="cancelUrl"
      >
        <div slot="checkout-button">
          <Button
            @action="checkout"
            :label="'Shut up and take my money!'"
          ></Button>
        </div>
      </StripeCheckout>
    </div>
  </MainContainer>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import MainContainer from 'src/layouts/MainContainer/Index.vue';
import Button from 'src/components/V2/Button/Index.vue';
import StripeCheckout from 'vue-stripe-checkout';

@Component({
  components: {
    Button,
    MainContainer,
    StripeCheckout
  }
})
export default class StripeCheckoutMobile extends Vue {
  private loading: boolean = false;
  private publishableKey: string = 'pk_test_';
  private successUrl = 'your-success-url';
  private cancelUrl = 'your-cancel-url';

  mounted() {
    console.log(this.$refs);
  }

  private checkout() {
    (this.$refs.checkoutRef as any).redirectToCheckout();
  }

  private go(route: string): void {
    this.$router.push(route);
  }
}
</script>
<style scoped>
.containerSucces {
  background-color: var(--secondary-background);
}

.add {
  display: flex;
  justify-content: center;
}
</style>

```
@jofftiquez Let me know if you need anything else! Thanks!

**Comment by jofftiquez** [comment]
@cmedinadeveloper can you try to import the component this way? `import { StripeCheckout } from 'vue-stripe-checkout';`?

**Comment by cmedinadeveloper** [comment]
With that change, the $ref object contains the method, but the button disappears, any clues? @jofftiquez 
![Screen Shot 2020-12-23 at 11 27 55 AM](https://user-images.githubusercontent.com/33674559/103012410-f3ae9e80-4511-11eb-8b88-748eb778ebf1.png)

**Comment by jofftiquez** [comment]
Can you use `template` instead of `div` as the `slot` container?

**Comment by cmedinadeveloper** [comment]
@jofftiquez Tried that, did not work :(

**Comment by jofftiquez** [comment]
This has something to do with how slot works in quasar? I'm not really sure. Anyhow, you can also place the button outside of the `StripeCheckout` component. Just put a blank div inside the `checkout-button` slot. Like so: 

```
<StripeCheckout
   ref="checkoutRef"
   :pk="publishableKey"
   :successUrl="successUrl"
   :cancelUrl="cancelUrl"
>
    <div slot="checkout-button">
       <div></div>
    </div>
</StripeCheckout>

<Button
  @action="checkout"
   :label="'Shut up and take my money!'"
  >
</Button>
```

**Comment by cmedinadeveloper** [comment]
@jofftiquez Tried that solution also, no luck :( 

I think it's related to the Stripe script is not being loaded, I will keep looking for solutions and post my findings

**Comment by jofftiquez** [comment]
That's weird. Yes please let me know if you find anything. It will help me to improve this plugin for the upcoming update. Thanks.

**Comment by jofftiquez** [comment]
Hello @cmedinadeveloper did you find anything? Thanks.

**Comment by jofftiquez** [comment]
I'm currently cleaning up the issues. Support for Quasar + Typescript is not really my priority right now. Still you can check if you properly registered the vue stripe plugin in the `boot` folder and quasar config file, otherwise there are cases when importing the component directly to the consuming component won't work. Closing this for now due to "no reply" reason. You can re-open this again if you find anything. Stay safe friend!

**Comment by bdkachadev** [comment]
Hi @jofftiquez

Have any solution for this.
I have same problem.

**Comment by ali-habibzadeh** [comment]
Same issue. Any work around?

**Comment by 9jadev** [comment]
Same Issue any work around?
