### ISSUE TITLE
TypeError: this.$refs.elementsRef.submit is not a function

### ISSUE THREAD

**Issue by AllanOricil** [vue-stripe/vue-stripe#159]
**Describe the bug**
![image](https://user-images.githubusercontent.com/55927613/104771269-ef208300-5769-11eb-9cb8-d8f652fc5820.png)

**To Reproduce**
````html
<template>
    <div class="d-flex flex-column">
        <stripe-elements
            ref="elementsRef"
            :pk="stripe.publishableKey"
            :amount="200"
            locale="de"
            @token="onReceiveToken"
            @loading="stripe.loading = $event"
            >
        </stripe-elements>
        <b-form>
            <label for="firstame">First Name</label>
            <b-form-input id="firstname"
                            v-model="firstname"
                            placeholder="First Name"
                            required>
            </b-form-input>

            <label for="lastname">Last Name</label>
            <b-form-input id="lastname"
                          v-model="lastname"
                          placeholder="Last Name"
                          required>
            </b-form-input>

            <label for="email">E-mail</label>
            <b-form-input id="email"
                          v-model="email"
                          type="email"
                          placeholder="Enter email"
                          required>
            </b-form-input>

            <label for="password">Password</label>
            <b-form-input id="password"
                          type="password"
                          aria-describedby="password-help-block"
                          v-model="password">
            </b-form-input>

            <b-button type="reset" 
                      variant="primary" 
                      @click="submit()">
                      Signup
            </b-button>
        </b-form>
    </div>
</template>

<script>
import { StripeElements } from 'vue-stripe-checkout';

export default {
    name: 'SignUp',
    components:{
        StripeElements
    },
    data: () => {
        return {
            firstname: null,
            lastname: null,
            email: null,
            password: null,
            stripe: {
                loading: false,
                amount: 1000,
                publishableKey: 'abacaxi', 
                token: null,
                charge: null
            },
        }
    },
    methods: {
        submit(){
            this.$refs.elementsRef.submit();
        },
        async onReceiveToken(token){
            const attributes = {
                firstName: this.firstname,
                lastName: this.lastname,
                email: this.email,
                password: this.password,
                metadata: { token } // Temporarily store this so our webhooks can do their thing
            }
            // Create the Keygen user
            const response = await fetch(`https://api.keygen.sh/v1/accounts/banana/users`, {
                method: "POST",
                headers: {
                    "Content-Type": "application/vnd.api+json",
                    "Accept": "application/vnd.api+json"
                },
                body: JSON.stringify({
                    data: { type: "users", attributes }
                })
            })
            const { data, errors } = await response.json()
            if (errors) {
                const message = errors.map(e => e.detail).toString()
                //register.parentNode.innerHTML = `An error occurred during user creation: ${message} (double check your ENV vars)`
                throw new Error(message)
            }
            // All good! The webhooks will handle the rest. :)
            //register.parentNode.innerHTML = `Thanks for your purchase, ${data.attributes.firstName}! 👊💥`
        }
    }
}
</script>

<style></style>
````

**Expected behavior**
As in shown in the example in the README, the component should have the submit() method accessible.

**Comment by jofftiquez** [comment]
Hello please use the latest version. Thank you.

**Comment by AllanOricil** [comment]
> Hello please use the latest version. Thank you.

**Comment by AllanOricil** [comment]
> Hello please use the latest version. Thank you.

Just update the NPM readme. I copied the example from there.

**Comment by jofftiquez** [comment]
Hello @AllanOricil you are right. Thank you.

**Comment by hkmsadek** [comment]
How did you solve it? facing similar issue.

**Comment by AllanOricil** [comment]
> How did you solve it? facing similar issue.

@hkmsadek I opened his lib inside .node modules and checked the exported components haha. The exported one is different than what is in the docs. If you can't figure out, tomorrow I post the name of the exported component.

**Comment by jofftiquez** [comment]
> > How did you solve it? facing similar issue.
> 
> @hkmsadek I opened his lib inside .node modules and checked the exported components haha. The exported one is different than what is in the docs. If you can't figure out, tomorrow I post the name of the exported component.

This is what's in the documentation:
![image](https://user-images.githubusercontent.com/8638243/105648263-8c578600-5ee5-11eb-83e6-d3213806c6ef.png)

And this is what's being exported:
![image](https://user-images.githubusercontent.com/8638243/105648277-9bd6cf00-5ee5-11eb-98a5-f5ca69bb5f4d.png)

Perhaps you're using the wrong version based on your code you are importing it from the old package: `import { StripeElements } from 'vue-stripe-checkout';`

**Comment by jofftiquez** [comment]
> @jofftiquez I got the source code I posted above from here "https://www.npmjs.com/package/vue-stripe-checkout" and I don't remember it was saying "deprecated". It also contained some examples in the readme. It was updated 9 days ago, one day after I opened this bug, and now it points to the right doc with the right examples, as you pointed out above. So this guy has probably used the wrong example from the, now deprecated, package and ended up with the same problem. 
> 
> @hkmsadek go to this page https://vuestripe.com/stripe-checkout/getting-started and follow the examples from there.

I understand, thank you. That was my bad. I apologise.

**Comment by hkmsadek** [comment]
Ok never mind and thanks, I have solved like this

I took a button and called a method
```
 pay(){
             this.$refs.elementRef.submit();
        },
```
this will trigger

tokenCreated method
and we can send that to server for the charge.
```
 async tokenCreated (token) {
            const data = await axios({
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json',
                },
                method: 'post',
                url: 'http://padelmobile.localhost/api/charge/club',
                data: token
            })
            console.log('data is ',data)
            console.log("token is ", token);
            // handle the token
            // send it to your server
            this.isLoading = false
        },

```
By the way, to to add stripe connect payment front end things as well please. not much code very simple code but yet vue plugin would be cool for people out there.

**Comment by jofftiquez** [comment]
Thanks 

> > > @jofftiquez I got the source code I posted above from here "https://www.npmjs.com/package/vue-stripe-checkout" and I don't remember it was saying "deprecated". It also contained some examples in the readme. It was updated 9 days ago, one day after I opened this bug, and now it points to the right doc with the right examples, as you pointed out above. So this guy has probably used the wrong example from the, now deprecated, package and ended up with the same problem.
> > > @hkmsadek go to this page https://vuestripe.com/stripe-checkout/getting-started and follow the examples from there.
> > 
> > 
> > I understand, thank you. That was my bad. I apologise.
> 
> @jofftiquez no problem. I'm looking forward to start using the other elements from your lib. Keep doing this great job.

Thanks @AllanOricil I'll keep you posted.

**Comment by jofftiquez** [comment]
> Ok never mind and thanks, I have solved like this
> 
> I took a button and called a method
> 
> ```
>  pay(){
>              this.$refs.elementRef.submit();
>         },
> ```
> 
> this will trigger
> 
> tokenCreated method
> and we can send that to server for the charge.
> 
> ```
>  async tokenCreated (token) {
>             const data = await axios({
>                 headers: {
>                     'Accept': 'application/json',
>                     'Content-Type': 'application/json',
>                 },
>                 method: 'post',
>                 url: 'http://padelmobile.localhost/api/charge/club',
>                 data: token
>             })
>             console.log('data is ',data)
>             console.log("token is ", token);
>             // handle the token
>             // send it to your server
>             this.isLoading = false
>         },
> ```
> 
> By the way, to to add stripe connect payment front end things as well please. not much code very simple code but yet vue plugin would be cool for people out there.

I'm glad you made it work. I will look into the Stripe connect usage, and see if there's anything that I can add from there.

**Comment by vmontoya19** [comment]
hi guys, my problem is same. It´s work everthing, but  in my console I see that ,
this.$refs.elementRef.submit() Property 'submit' does not exist on type 'Vue'. 
![asi](https://user-images.githubusercontent.com/115263572/204541476-9e25f7b0-43bd-4427-8114-6a9e924d6a61.PNG)
