### ISSUE TITLE
How to generate token when using vue stripe element card?

### ISSUE THREAD

**Issue by hkmsadek** [vue-stripe/vue-stripe#160]
**Describe the bug**
In the documentation, it has generate token button but in code the button code is missing. If hit enter after adding card cvc zip, it gives me a token, but how can I add a button and based on button click how can I get the token>

Here is the code I am trying to use 
```html
<template>
  <div>
    <stripe-element-card
      ref="elementRef"
      :pk="pulishableKey"
      @token="tokenCreated"
    />
  </div>
</template>

<script>
import { StripeElementCard } from '@vue-stripe/vue-stripe';
export default {
  components: {
    StripeElementCard,
  },
  data () {
    this.pulishableKey = process.env.STRIPE_PUBLISHABLE_KEY;
    return {
      token: null,
    };
  },
  method: {
    tokenCreated (token) {
      console.log(token);
      // handle the token
      // send it to your server
    },
  }
};
</script>
```

If you hit enter, it generate a token in the method, but I want to generate from a button click.

**Comment by jofftiquez** [comment]
May I see how you implemented the button? Thanks.

**Comment by hkmsadek** [comment]
Ok never mind and thanks, I have solved like this 

I took a button and called a method
```
 pay(){
             this.$refs.elementRef.submit();
        },

```
this will trigger 

`tokenCreated` method 
and we can send that to server for the charge. 

```
 async tokenCreated (token) {
            const data = await axios({
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json',
                },
                method: 'post',
                url: 'http://padelmobile.localhost/api/charge/club',
                data: token
            })
            console.log('data is ',data)
            console.log("token is ", token);
            // handle the token
            // send it to your server
            this.isLoading = false
        },


```



By the way, to to add stripe connect payment front end things as well please. not much code very simple code but yet vue plugin would be cool for people out there.

**Comment by jofftiquez** [comment]
https://github.com/vue-stripe/vue-stripe/issues/159#issuecomment-767211450
