### ISSUE TITLE
Unsupported locale breaks payment flow

### ISSUE THREAD

**Issue by stefanb** [vue-stripe/vue-stripe#162]
**Describe the bug**
User normally expects to make the payment in the same language as he is using the site with, so developers tend to pass the same locale to stripe. When user is using the website in a language not supported by stripe the checkout just BREAKS with NO visible clue, except in the javascript console.

A workaround in our project was to use `auto` locale specifically for such unsupported language: https://github.com/sledilnik/website/commit/97e86335e1c94dc79acefbdd0377eba3f348cd4b
Unfortunately we'd have to check with every new language what its Stripe support status is, while this could be easily checked by vue-stripe against a list of supported locales and falling back to `auto`, and possibly write a warning to javascript console. 
If Croatian language one day gets supported our app will likely still be using the 'auto', unnecessarily still confusing some users with sudden language change.

**To Reproduce**
1. specify `locale='hr'`
2. Go to checkout
3. Nothing happens
4. See error in the javascript console: `react_devtools_backend.js:2430 IntegrationError: Invalid value for stripe.redirectToCheckout: locale should be one of the following strings: auto, bg, cs, da, de, el, en, en-GB, es, es-419, et, fi, fr, fr-CA, hu, id, it, ja, lt, lv, ms, mt, nb, nl, pl, pt, pt-BR, ro, ru, sk, sl, sv, tr, zh, zh-HK, zh-TW. You specified: hr.`

**Expected behavior**
Checkout should be made with `auto` locale

**Comment by jofftiquez** [comment]
Hello @stefanb thank you for this. I understand the problem, I will update the local list of locales in vue-stripe and add a fallback to `auto` in case the user specifies a non-supported locale. Can you confirm if this will work for you?

**Comment by stefanb** [comment]
Yes, that would be fine. 👍 
It would require some occasional whitelist maintenance in this project. Alternative way would be to call Stripe and if it fails try with `auto`? I'm not sure if this is doable, nor do i know how stripe handles invalid locales (where this error message originates from?), maybe they already fallback to auto?

**Comment by jofftiquez** [comment]
@stefanb

Awesome!

I think having an occasional update for the supported locales would be more efficient than doing a call every attempt to checkout to Stripe, this will add an overhead to the process. In any case I'm always available for improvements like this. I will try to release the fixed version today after my work. I'll reference this issue. Thanks again.

**Comment by stefanb** [comment]
No rush, the workaround is working so we can find the best solution.
Alternatively there could be a new `preferredLocale` option (heavily "advertised" in the docs next to `locale` option) with such fallback and let the users of current `locale` option handle `error` events?

**Comment by jofftiquez** [comment]
Hmm I'm that's also another way to put it. I'll check it as well. Thanks.

**Comment by jofftiquez** [comment]
Hello @stefanb in the end I decided to do the fallback solution. Kindly check the [diff here](https://github.com/vue-stripe/vue-stripe/pull/163/files). New version is `v4.1.1`. Let me know if there's any more I can do to help you.

**Comment by stefanb** [comment]
Thanks!

I have prepared a PR with the new v4.1.1 at https://github.com/sledilnik/website/pull/822 
to be tested thoroughly at https://pr-822.preview.sledilnik.org/hr/donate and other languages.
