### ISSUE TITLE
iframe is not removed when component is destroyed

### ISSUE THREAD

**Issue by freakypie** [vue-stripe/vue-stripe#165]
An iframe appears to be created when stripe is initialized, but it is not removed when the component is destroyed. Each time the component is mounted another iframe is added to the document.

**Comment by jofftiquez** [comment]
Hello @freakypie, thank you for submitting an issue. Would you mind sending a screenshot? Please also include the version, and how you are implementing it. Thanks! 

For destroying tho, there's a method available for that, you can access it via ref like so:

```js
this.$refs.cardRef.destroy();
```

**Comment by jofftiquez** [comment]
Hello, any feedback on this? Closing this for now, kindly re-open or create a new issue if you find anything odd again. Thank you. Stay safe.
