### ISSUE TITLE
stripe checkout component doesn't display

### ISSUE THREAD

**Issue by jlbousing** [vue-stripe/vue-stripe#166]
Hi, I open this issues because stripe-checkout component doens't display like the examples...I don't know what I did wrong. 

`<transition name="modal">
            <div class="modal-mask">
                <div class="modal-wrapper">
                    <div class="modal-container">

                        <div class="modal-header">
                            <slot name="header">
                                Pay
                            </slot>
                        </div>

                        <div class="modal-body">

                            <stripe-checkout
                                ref="checkoutRef"
                                :pk="pk"
                                :successUrl="successUrl"
                                :cancelUrl="cancelUrl"
                            >
                                <div slot="checkout-button">
                                    <div>Pay now</div>
                                </div>
                            </stripe-checkout>

                            <Button
                                @action="checkout"
                                :label="'Shut up and take my money!'"
                            >
                            </Button>

                        </div>

                        <div class="modal-footer">
                            <slot name="footer">
                                <button class="float-right bg-red-500 border-2 rounded-full text-white"
                                        @click="$emit('close')">
                                    Close
                                </button>
                            </slot>
                        </div>
                    </div>
                </div>
            </div>
        </transition>
    </div>
</template>`

I declared the component in main.js like this 
`
import { StripeCheckout } from '@vue-stripe/vue-stripe';

Vue.component("stripe-checkout",StripeCheckout);
`
 call the component inside of a modal...but I think that doesn't matters... when I compile, the body of modal is empty...somebody can help me ?

**Comment by jofftiquez** [comment]
Hello may I know if there are errors? Please follow the latest documentation in the website https://vuestripe.com

I noticed that you are using the old way of rendering the checkout button. The slot `checkout-button` is no longer available. You can just simply add the button on the same level as the checkout button.

**Comment by jlbousing** [comment]
Yeah, I tried too. But is not rendering. I don't know why and there not errors in browser console

like this:

`
   <stripe-checkout
                                ref="checkoutRef"
                                mode="payment"
                                :pk="pk"
                                :line-items="lineItems"
                                :success-url="successUrl"
                                :cancel-url="cancelUrl"
                                @loading="v => loading = v"
                            />
                            <button @click="checkout">Pay now!</button>
`

this is like https://vuestripe.com/stripe-checkout/one-time-payment but is not rendering...the form doesn't show :(

**Comment by jofftiquez** [comment]
Hi, what version are you using? Please provide the whole component code. What happens when you click the "Pay now!"? Kindly provide the errors.

**Comment by jlbousing** [comment]
Hi again.  "@vue-stripe/vue-stripe": "^4.1.1"  is the lastest right ? 

when I click just execute this.$refs.checkoutRef.redirectToCheckout and then give me a 400 error...because I need create a plan in stripe, something like that...I just testing...but I think the code that I show you it must show me the form where the user enter the card number, CVC, etc...but nothing happend :( and no errors too

**Comment by jofftiquez** [comment]
In this documentation https://vuestripe.com/stripe-checkout/one-time-payment/ did you follow steps 1 and 2? Enable Checkout, and Create products and prices? 

Also make sure you're passing the proper `lineItems`. Please show me your code.

**Comment by jlbousing** [comment]
Well...in my dashboard, checkout is enabled and I created the product:

lineItems is like this:

` data(){

            return{
                pk: process.env.STRIPE_PK,
                successUrl: `${process.env.APP_URL}/pay-success`,
                cancelUrl: `${process.env.APP_URL}/pay-cancel`,
                lineItems: [
                    {
                        price: 'prod_IvBuLQU0JD57LR',
                        quantity: 1,
                    }
                ],
            }`

price is the ID price of my product...that value must right there, isn't ?  I have another question, Can I doesnt register the domain in the one-time integration options to test in localhost ?

**Comment by jlbousing** [comment]
HEY MAN I FUCKING DID IT!!!!! YEAHH 

in the price I was enter the prodID not the Price ID...I tried and I did it!!!! 

Thank you so much brother, I love you...greetings from Venezuela

**Comment by jofftiquez** [comment]
Nice @jlbousing I'm glad you did it!
