### ISSUE TITLE
Ability to create a payment method instead of token for elements

### ISSUE THREAD

**Issue by tommerrett** [vue-stripe/vue-stripe#170]
**Is your feature request related to a problem? Please describe.**
Creating stripe tokens has been deprecated by stripe and the new architecture uses payment methods and payment intents. Add ability in stripe elements card to create payment intents instead of payment methods.

**Describe the solution you'd like**
Ability to create a payment method using the elements card as per stripe-js documentation (https://stripe.com/docs/js/payment_methods/create_payment_method)

I am happy to work on a pull request if you are open to this feature request. If so, please just describe the component API design that you would like me to follow.

**Comment by jofftiquez** [comment]
Hello, this is possible in the current setup, it's just not documented yet. But please follow [this thread](https://github.com/vue-stripe/vue-stripe/issues/164). 

The documentation task is currently on my pipeline and if there's a better way than the current please describe it here so we can collab and the work won't be doubled. Thanks.

**Comment by tommerrett** [comment]
Thanks - this will do for now. Probably a good pattern to just interact directly with the stripe-js api as you suggest.

**Comment by jofftiquez** [comment]
Yeah. If you think of anything that might help this project, don't hesitate to throw around your thoughts. Thanks man!
