### ISSUE TITLE
Rendering Error when rendering stripe-checkout (e is not a function)

### ISSUE THREAD

**Issue by DominicFinn** [vue-stripe/vue-stripe#171]
**Describe the bug**
Use the [recurring payment example on the vue stripe website](https://vuestripe.com/stripe-checkout/recurring-payment) in a clean Vue project. I have used Vue3 but stuck to the Vue2 style options layout in the example (an exact copy and paste). 

I visit the view containing the component and get a console error that `e is not a function()` in the render function. Looking at the source code I can see `e` is supposed `createElement ` function but when I insert a console.log the actual value of createElement is:

`"{"mode":"subscription","lineItems":[{"price":"private","quantity":1}],"successUrl":"my url","cancelUrl":"my url","billingAddressCollection":"auto","clientReferenceId":"user id","locale":"auto","disableAdvancedFraudDetection":false,"_$coertions":[["locale",null]],"$coerced":{"locale":"auto"}}"
`

**To Reproduce**
1. Go to 'install 4.1.4', in a new Vue(3) project, create a view/route and copy and paste example from https://vuestripe.com/stripe-checkout/recurring-payment (with some valid values in it)
2. Run project
3. Go to route

**Expected behavior**
The component to render on the view (in this case, the button)

**Screenshots**
# ![Capture](https://user-images.githubusercontent.com/697551/108134426-1f7f7800-70ae-11eb-863b-873990dda73d.PNG)

**Desktop (please complete the following information):**
 - OS: windows/mac
 - Browser chrome / edge
 - Version any

**Additional context**

It's worth saying, I noticed that 'render' was changed recently (commit 57ca7d8f72b6cb688d8ba716a0ee2d41e52f5f42) from template so I changed this back locally to 'template: '<div></div>',' built locally and tested it out and it works as expected.  

My wildcard is that I am using Vue3, I don't think it should matter but it seems important to mention.

**Comment by jofftiquez** [comment]
Hello @DominicFinn thank you for this detailed issue. It will help me a lot in solving this. 

It could be that you're using vue3 but I can't be sure until I dig deeper. 

I changed the template to render because it is the more proper way of creating a non .vue component. Also, if I remember it correctly there's some issue with the vue linter so I had to change it to render. I can't really remember but I'm sure I had a good reason for doing that. Sorry, my memory is bad. 😆 

Anyway, I will look into this. Thanks a lot.

**Comment by DominicFinn** [comment]
"I changed the template to render because it is the more proper way of creating a non .vue component"

Thanks for this, I am relatively new to Vue and it's ways of doing things! 

Interestingly, I noticed above, that in render, it's actually the element that get's passed into it. So when I just return the element, everything works as expected. 

```
  render (createElement) {
    return createElement;
  },
```
