### ISSUE TITLE
How do I load the card when the customer is registered in the setup?

### ISSUE THREAD

**Issue by N3R00** [vue-stripe/vue-stripe#175]
How do I load the card when the customer is registered in the setup?

**Comment by N3R00** [comment]
I generate a setup session for the customer to save their card for future use, however, I need to pay a payment or subscription to the customer's card to be loaded, and this is not happening.

**Comment by jofftiquez** [comment]
Hi, with this setup I believe you have to do most of the work in the backend. Create a Session with the subscription details, fetch the Customer you saved from stripe and attach it in the Session, then use the Session#id in the checkout in frontend. I'm not entirely sure if this the right way but you can always check the Sessions docs.

**Comment by N3R00** [comment]
that's exactly what I do, but it still doesn't work.
When creating the Session I put the customer id

**Comment by Faks** [comment]
the funny part is that that there is a bug inside stripe-checkout component so to fix this you have to pass 
` :lineItems="[]"
`
also were checking typescript code and there is a bug a for the line  
` lineItems: Array<any> | null
`; 
**but should be**
`   lineItems: Array<any> = [];
`

**Comment by jofftiquez** [comment]
Hello @Faks thank you for pointing those out. I am not really familiar with TypeScript typings, a PR would be a big help. Thank you.

**Comment by jofftiquez** [comment]
For the bug that you are talking about @Faks, would you mind pointing out the specific problematic part? 

In the prop `lineItems: { type: Array, default: [], },` will not work as vue requires the default value to be a function for Objects and Arrays.

**Comment by jofftiquez** [comment]
@N3R00 hello, were you able to make it work? 

Upon checking the documentation for Sessions, you can try [`customer`](https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-customer) field. 

If I understand your process correctly, this is how I would do it. 

1. Get the user's email and other details, then use [Customers](https://stripe.com/docs/api/customers) API to save the user.
2. Create a payment source for the user using Stripe elements as seen here https://vuestripe.com/stripe-elements/card, then attach the created source to your customer data. See https://stripe.com/docs/api/customers/update
3. Create a Session for the subscription flow. In this Session, try to use put the Customer ID to `customer` field.
4. Use the session id to checkout.

**Comment by Faks** [comment]
@jofftiquez Hey, sorry little busy later on evening will give more details, but now I create session on laravel api then, use session id on package that in my vue spa/pwa and then in component add :lineItems="[]" and it will work since by default it expects to have lineItems but empty array is enough to make it work since session is all ready started and do the redirect.

**Comment by jofftiquez** [comment]
@Faks I guess I understand now. Altho it might not be exactly a "bug", but I understand how it can cause confusion. The `lineItems` should be rejected if the `sessionId` already has a value. 

In reality the `lineItems` was never used when the user is using the `sessionId` as you can see in [this line](https://github.com/vue-stripe/vue-stripe/blob/556df74410b6a8887ef8c6c3777505dcf21efe3a/src/checkout/index.js#L24) there is a return statement. 

No matter what props you pass to the component, as long as the `sessionId` is present, they will be useless. 

Maybe I'll just clarify it in the documentation. This matter is not related to @N3R00's issue.

**Comment by jofftiquez** [comment]
Closing this due to lack of feedback. Please open a new issue if you find anything odd again. Thank you. Stay safe everyone!
