### ISSUE TITLE
How can i use a function to test stripe checkout?

### ISSUE THREAD

**Issue by matiasfanger** [vue-stripe/vue-stripe#177]
Currently im using `this.$refs.checkoutRef.redirectToCheckout();` but its give me this error:

`Uncaught (in promise) IntegrationError: The Checkout client-only integration is not enabled. Enable it in the Dashboard at https://dashboard.stripe.com/account/checkout/settings.`

There is a function to just see if everything is working fine? Thanks.

![imagen](https://user-images.githubusercontent.com/39188240/109636045-dad1f300-7b29-11eb-89c6-f179c6714466.png)

**Comment by jofftiquez** [comment]
Based on the error, you need to enable checkout first in your Stripe dashboard
