### ISSUE TITLE
Allow stripe sdk to be loaded with crossorigin

### ISSUE THREAD

**Issue by LolkeAB** [vue-stripe/vue-stripe#181]
**Is your feature request related to a problem? Please describe.**
Currently, when you're adding the `Cross-Origin-Opener-Policy: same-origin` header to your website (which is required for certain WASM features (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements), loading of the stripe SDK will be blocked by the browser. This can be prevented with adding the `crossorigin` attribute to the `<script>` tag
![image](https://user-images.githubusercontent.com/7376634/111747808-10980b00-8890-11eb-8431-44bc016ec254.png)

**Describe the solution you'd like**
Optionally add the `crossorigin` attribute to the `script` tag when loading the Stripe SDK.

**Describe alternatives you've considered**
Removing the `Cross-Origin-Opener-Policy: same-origin` header on the page with the Stripe Checkout. But this is impossible with a SPA.

**Comment by LolkeAB** [comment]
Hmm nevermind, the proposed fix will make the SDK load correctly, however any further steps (actually loading the Stripe html/js) still fails because of CORP.

**Comment by jofftiquez** [comment]
@LolkeAB am not really sure, but, typically the fix to CORS error are done in the backend.
