### ISSUE TITLE
Check integration of coupons & add to docs if available

### ISSUE THREAD

**Issue by jofftiquez** [vue-stripe/vue-stripe#183]
https://github.com/vue-stripe/vuestripe.com/issues/5

> It would be really nice to extend the integration with coupons and taxes. So far the documentation does not state how or if this integration is possible. Thank you for any help!

**Comment by abstraktion-io** [comment]
Will it be possible?

**Comment by jofftiquez** [comment]
@abstraktion-io I haven't really checked the docs related to this yet, apologies, I am currently on a leave. This is noted tho.

**Comment by jofftiquez** [comment]
Hello @abstraktion-io apparently `Coupons` may only be applied to `Invoices`, or `Orders`, and these are done in the backend. You can however [use `Session#discounts.coupon` to accept a discount coupon](https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-discounts-coupon) and use the [session id to checkout](https://vuestripe.com/stripe-checkout/sessions-generator). I hope this helps. Stay safe.
