### ISSUE TITLE
v4.1.8 and nuxt@2.15.3

### ISSUE THREAD

**Issue by EnterpriseWide** [vue-stripe/vue-stripe#186]
**Describe the bug**
Installation of vue-stripe@4.1.8 as per the doco on a new nuxt@2.15.3 app fails to run as soon as you visit a page with the vue-stripe being used on it

**To Reproduce**
1. install new nuxt app using 'npm init nuxt-app stripe1'
2. npm install --save @vue-stripe/vue-stripe
3. StripeCheckout to the index page as described here - https://vuestripe.com/stripe-checkout/one-time-payment
4. npm run dev
5. open http://localhost:3000

**Expected behavior**
The page should just run and show the button

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge
 - Version latest

![image](https://user-images.githubusercontent.com/1875225/113116850-92f1d900-9259-11eb-90a5-f8eafaf64af6.png)

**Comment by jofftiquez** [comment]
Hello @EnterpriseWide have you checked this? https://vuestripe.com/nuxt. Thanks.

**Comment by EnterpriseWide** [comment]
Yeah, I saw that, thank you for putting that together. I was concerned that it did not use @vue-stripe/vue-stripe@4.1.8 but instead used vue-stripe-checkout@3.5.14-beta.0
So I ruled out trying to understand it because it was an older Major version and it is using a beta.
I'll try updating it to use @vue-stripe/vue-stripe

**Comment by jofftiquez** [comment]
@EnterpriseWide I understand, it was an outdated one. If you want to look at the setup for the new one, I am always updating the version for @vue-stripe/vuestripe.com.

**Comment by jofftiquez** [comment]
Hi, @EnterpriseWide closing this for now. Just let me know if you need any more help. Thanks.
