### ISSUE TITLE
Server-Side Rendering Bug

### ISSUE THREAD

**Issue by sillvva** [vue-stripe/vue-stripe#188]
**Describe the bug**
Just importing the component into my Nuxt page is causing an error when loaded via server-side rendering.

The issue is in `@vue-stripe/vue-stripe/dist/index.js`

**To Reproduce**
1. Create a nuxt app with server-side rendering
2. Add the component to a page.
3. Use `npm run dev` to run the page in developer mode

**Expected behavior**
I expect the use of `window` on the server side is causing the error. The component should check for the existence of window or use some other means to determine if the component is loaded in the browser to determine whether or not to use window.

**Screenshots**

![img](https://i.imgur.com/F2kzsPC.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Any

**Comment by jofftiquez** [comment]
Hi @sillvva what a timing, I'm working on this project right now. Have you checked [this](https://vuestripe.com/nuxt)?

**Comment by sillvva** [comment]
I haven't seen it. Does this mean I just need to wait for an update, and then update the module?

**Comment by jofftiquez** [comment]
@sillvva you just have to do a specific setup for it to work with nuxt smoothly. If you want I can check your project again and give you some pointers.

**Comment by sillvva** [comment]
That would help a lot. You rock!

https://github.com/sillvva/mattdekok.dev/tree/master/frontend

**Comment by jofftiquez** [comment]
I'll check it out.

**Comment by sillvva** [comment]
Actually, I figured it out following your Github instructions!

https://github.com/vue-stripe/vue-stripe-checkout-nuxt-demo

Thanks! Sorry if I wasted your time.

**Comment by jofftiquez** [comment]
Hi @sillvva I saw this late, I created a PR https://github.com/sillvva/mattdekok.dev/pull/69 haha. Anyway, I'm glad you figured it out.  Thanks.
