### ISSUE TITLE
As developer I want SSR support for vue-stripe card element

### ISSUE THREAD

**Issue by devictoribero** [vue-stripe/vue-stripe#189]
**Is your feature request related to a problem? Please describe.**
When using `vue-stripe` in NuxtJS SSR it throws the following error 👇:
```javascript
ReferenceError
window is not defined
```

My code is the following 👇
```
<template>
  <div>
    <div v-if="isMounted && isStripeLoaded">
      <StripeElementCard v-if="isStripeLoaded" :pk="publishableKey" />
      <button @click="pay" type="button">Pay</button>
    </div>
    <div v-else>stripe is NOT loaded</div>
  </div>
</template>
```

**Describe the solution you'd like**
I would expect that the library is only executed on the client-side, so this error is not thrown

**Describe alternatives you've considered**
I've tried to lazy load the component, but anyways it's executed so the error is thrown 👇:
```
export default {
  components: {
    StripeElementCard,
  },
  data() {
    return {
      publishableKey: null,
      isMounted: false,
      isStripeLoaded: false,
    };
  },
  **async beforeCreate() {
    const { publishableKey } = await getPublishableKeyAsync()

    return publishableKey
  },
  mounted() {
    this.isMounted = true;
  },
  head() {
    return {
      script: [
        {
          hid: "stripe",
          src: "https://js.stripe.com/v3/",
          defer: true,
          callback: () => {
            this.isStripeLoaded = true;
          },
        },
      ],
    };
  },
};
</script>
```

_PS: I'm 2 months old using VueJS and NuxtJS so I might be missing something._

**Comment by devictoribero** [comment]
I've seen that a year ago approx, an [issue was opened in order to give support to SSR for the stripe checkout](https://github.com/vue-stripe/vue-stripe/issues/72), but I find nothing related to the `CardElement`.

_PS: I've checked the [StripeCardElement codebase](https://github.com/vue-stripe/vue-stripe/blob/master/src/elements/Card.vue) and I don't understand why this error is prompted. The `mounted()` hook is only executed in the client-side, isn't it? If so, why this error is happening?_

**Could a solution be to import the module on the `mounted hook`?** Kinda like 👇:
```javascript
mounted() {
   const { loadStripe } = require('@stripe/stripe-js/dist/pure.esm.js');
   ...
}
```

**Comment by jofftiquez** [comment]
Please see the Working With Nuxt section in the documentation. Thanks.

**Comment by devictoribero** [comment]
@jofftiquez thank you for the hin 🙏t! I've coded myself the same, but even it's a different, I still get one error. As you can see in [my last commit](https://github.com/CrystallizeAPI/crystallize-nuxtjs-boilerplate/commit/df956cb162c82c839f163a9f3d90de4967aac027) I added the plugin:

```javascript
import Vue from 'vue';
import { StripeCardElement } from '@vue-stripe/vue-stripe';

export default () => {
  Vue.component('StripeCardElement', StripeCardElement);
};
```

I also added the`nuxt.config.js` needed configuration
```javascript
/*
   ** Plugins to load before mounting the App
   */
  plugins: [
    { src: '~/plugins/stripe-card-element.js', mode: 'client' }
  ],
```

and I'm using the component:
```javascript
<template>
  <div>
    <div v-if="isMounted && isStripeLoaded">
      <StripeCardElement   // <-- As you can see here
        v-if="isStripeLoaded"
        :pk="publishableKey"
        @token="handleStripeToken"
      />
      <button @click="handlePayment" type="button">Pay</button>
    </div>
    <div v-else>stripe is NOT loaded</div>
  </div>
</template>
```

⚠️ I don't get the same window not defined error, which is awesome! **But I get an error that says:**
```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Unknown custom element: <StripeCardElement>
- did you register the component correctly?
For recursive components, make sure to provide the "name" option.
```

_FYI : I'm using the NuxtJS autoimport feature_

**Comment by jofftiquez** [comment]
Hmm that's odd. I still need look at it. I will fork your current repository that has the problem so I can reproduce and debug it. Just give some time to figure it out. I'm currently on a weekend vacation I don't have access to my machine. Please keep me posted here. Thank you.

**Comment by devictoribero** [comment]
Sure thing. Have fun 🌞 ! Meanwhile, I'll investigate it because it's a blocking issue for me.

It might be related to the auto-import feature of who-knows-what.

**Comment by weihao** [comment]
Following from
https://github.com/vue-stripe/vue-stripe/issues/72

**Comment by jofftiquez** [comment]
Hello, @devictoribero I just got back. I'll schedule this today or tomorrow. PHT. Thanks. Let me know if you found anything. Cheers!

**Comment by devictoribero** [comment]
@jofftiquez I haven't been able to make it work. :(

**Comment by devictoribero** [comment]
⚠️ **UPDATE @jofftiquez : Totally my bad**. I was doing `import {StripeElementCard} from '...'` instead of `import {StripeCardElement} from '...'`. This was why the plugin was not working and the framework was throwing an error of component not registered.

I've seen also that instead of creating a plugin and registering the component, a better workaround and more intuitive is to wrap the instance of the component with the NuxtJS `<client-only>` component.

**Anyway, I'll do a PR to fix the issue and to don't be SSR breaking**

**Comment by jofftiquez** [comment]
@devictoribero I'm glad you figured it out man. 🤘

**Comment by jofftiquez** [comment]
Closing this for now. Kindly re-open if the issue persists. Thanks.
