### ISSUE TITLE
Support stripe checkout "metadata"

### ISSUE THREAD

**Issue by fyllepo** [vue-stripe/vue-stripe#192]
Hello! thanks for your work on this package, do you have plans to include metadata for stripe checkout? I realised you've not provided the prop for it.

**Comment by fyllepo** [comment]
Ah, apologies, looking a big closer at the API it's required to create a session with metadata and then attach a session id

**Comment by jofftiquez** [comment]
No problem @fyllepo, thank you for using vue-stripe 😄
