### ISSUE TITLE
Please provide a nuxt + vuetify example using stripe-element-card

### ISSUE THREAD

**Issue by Megachill** [vue-stripe/vue-stripe#193]
**Is your feature request related to a problem? Please describe.**
As per summary, please provide a vuetify example for stripe-element-card that would render properly with vuetify. Current stripe-element-card is not scaling proper and styles seem to be broken

**Describe the solution you'd like**
Please provide an example, like in this [thread](https://github.com/vue-stripe/vue-stripe/issues/164#issuecomment-775662590)

**Comment by jofftiquez** [comment]
It is not possible to use vuetify component directly in the elements because Stripe sdk is mounting native input. What you can do is make use of the `elementStyle` property to make it look like vuetify component. What you see in the docs is not broken, it's intentionally bare. 

If you have any more questions please let me know, thanks.

**Comment by Megachill** [comment]
Thank you @jofftiquez - i understand what you're saying. I am not a UI designer or CSS pro by any means, if anybody has done the styling bit, i'd be super interested in how you achieved this.

**Comment by jofftiquez** [comment]
Totally understand @Megachill we have the same struggle with CSS 🤣🤦‍♂️

**Comment by Megachill** [comment]
So I ended up using the Stripe Plugin you provide and build my own. Somewhat looks ok now. Only thing off putting is that sometimes I am getting 

`this.$stripe is undefined`  in my console and the page crashing. Ans so this seems to be when the computed piece is still doing its thing but I am attempting to mount `cardNumber` and the other fields to `stripeElements`
