### ISSUE TITLE
redirectToCheckout function is not working

### ISSUE THREAD

**Issue by jmodanwal** [vue-stripe/vue-stripe#197]
Hi,
I am trying to implement stripe plugin in my nuxt js project and followed these steps https://github.com/vue-stripe/vue-stripe-checkout-nuxt-demo#setup
When I try to call method to redirect checkout page then it's giving error : this.$refs.checkoutRef.redirectToCheckout is not a function

Can you please tell me what am I doing wrong?

![stripe-elements](https://user-images.githubusercontent.com/54843020/117778960-d463a400-b25b-11eb-8f27-f55b611cbe75.png)
![stripe-script](https://user-images.githubusercontent.com/54843020/117778987-daf21b80-b25b-11eb-9815-eeccbbc1e1f9.png)

Thanks

**Comment by jofftiquez** [comment]
Hi, can I see how you implemented steps 3, and 4 in [this guide](https://github.com/vue-stripe/vue-stripe-checkout-nuxt-demo#setup)?

And a screenshot of your dev console perhaps? Thanks.

**Comment by jmodanwal** [comment]
> Hi, can I see how you implemented steps 3, and 4 in [this guide](https://github.com/vue-stripe/vue-stripe-checkout-nuxt-demo#setup)?
> 
> And a screenshot of your dev console perhaps? Thanks.

Step 3 : 
![vue-stripedotjs](https://user-images.githubusercontent.com/54843020/117798486-d4b96a80-b26e-11eb-94b1-98729639b66f.png)

Step 4: 
![nuxt-config](https://user-images.githubusercontent.com/54843020/117798558-e26ef000-b26e-11eb-84fb-c84937572308.png)

Console error on click:
![console-error](https://user-images.githubusercontent.com/54843020/117799441-bb64ee00-b26f-11eb-9089-ad52d4971e94.png)

**Comment by jofftiquez** [comment]
Hi, thanks. I'm gonna check it out.

**Comment by jmodanwal** [comment]
Thanks :)
