### ISSUE TITLE
Question: How to prevent Stripe from creating a new customer for every client-side checkout?

### ISSUE THREAD

**Issue by richdunajewski** [vue-stripe/vue-stripe#203]
I'm using the client-only integration to allow people to subscribe to either a monthly or annual subscription plan. Every time a checkout is performed, Stripe will create a new customer even though I'm passing the same customerEmail address in, as well as the same clientReferenceId which in my case is my own ID for the user, so I can match up the webhook event to the user by ID when the event comes in.

Is there a way to avoid creating multiple customers in Stripe? Would the only option be to manually manage the customer manually via API on the server-side and do a normal checkout session created on the server?

**Comment by jofftiquez** [comment]
Hello @richdunajewski, I don't know if such a thing exists yet in the client-only integration. What I can suggest is to use Sessions. You can attach existing customers in a Session (I think). Let me check this as well so I can help you. Thanks for posting an issue.

**Comment by richdunajewski** [comment]
I went ahead and created a session on the server side, which let me attach metadata to the customer and session so I could more easily process the webhook and associate the subscription with the right user in my database.

We can close this, as I think this is the right solution. Without passing in a customer ID to Stripe, they're going to always create a new customer record.

**Comment by Vitomir2** [comment]
@richdunajewski what is the difference using the straightforward Checkout or the Session Checkout?
