### ISSUE TITLE
Success URL return with empty data

### ISSUE THREAD

**Issue by warrence** [vue-stripe/vue-stripe#204]
When im using one time payment, everything works well, but in the return to the success url after stripe payment, it didn't return anything to the success url, is that normal? I may need the payment details for logging.

**Comment by jofftiquez** [comment]
Hello, @warrence that's totally normal. If you want to handle the after hook of the checkout, you can either use Sessions to predetermine the user data like customerId, email, etc., or webhooks to watch for events like Subscriptions, Billings, etc. I will be closing this for now. Thanks for posting an issue. Let me know if you need more help.
