### ISSUE TITLE
Documentation for Recurring Stripe Checkout is OOD

### ISSUE THREAD

**Issue by 2Clutch** [vue-stripe/vue-stripe#206]
I'm trying to implement Stripe Checkout for a subscription for my Vue 2 app. I've used the following links as references:
1. https://vuestripe.com/stripe-checkout/recurring-payment
2. https://randomcodetips.com/recurring-stripe-checkout-payment-in-vue-js/

Using the content found in the 2 links above, I came up with the following:
```<template>
  <stripe-checkout
      ref="checkoutRef"
      mode="subscription"
      :pk="pk"
      :items="items"
      :successUrl="successUrl"
      :cancelUrl="cancelUrl"
  >
    <template slot="checkout-button">
      <button @click="checkout">Subscribe!</button>
    </template>
  </stripe-checkout>
</template>

<script>
import { StripeCheckout } from '@vue-stripe/vue-stripe';

export default {
  components: {
    StripeCheckout
  },
  data: () => ({
    loading: false,
    pk: process.env.VUE_APP_STRIPE_PUBLISHABLE_KEY,
    items: [
      {
        price: 'price_id', # membership_tier_1
        quantity: 1,
      },

      {
        price: 'price_id', # membership_tier_2
        quantity: 1,
      },

      {
        price: 'price_id', # membership_tier_3
        quantity: 1,
      },

    ],
    successUrl: '/',
    cancelUrl: '/',
  }),
  methods: {
    checkout () {
      this.$refs.checkoutRef.redirectToCheckout();
    }
  }
}
</script>
```

When I visit the relevant route, I see a blank page. Per my understanding, I should see `3 "Subscribe" buttons`. I've enabled the Client-Side Integration in my Stripe dashboard and followed the Vue Stripe documentation to the letter, which as far as I can tell only ask for the package to be installed via npm or yarn (I used npm).

The event described above leads me to believe the documentation is OOD. If I'm mistaken, please let me know.

**Comment by jofftiquez** [comment]
Hello @2Clutch, you are using the "deprecated" way of implementing the checkout component in the template from what I see in your snippet. The slot `checkout-button` no longer exists. If you followed the example exactly from https://vuestripe.com/stripe-checkout/recurring-payment/, it should work. 

Regarding the `3 "Subscribe" buttons`, it doesn't work that way. You should still implement 1 checkout for each tier, or programmatically manipulate the `lineItems` value based on the tier chosen by the user. See my implementation here: https://github.com/vue-stripe/vuestripe.com/blob/master/pages/stripe-checkout/recurring-payment.vue
