### ISSUE TITLE
How to handle change event in Card elements?

### ISSUE THREAD

**Issue by trdonnisedavid** [vue-stripe/vue-stripe#208]
Hi there, I am currently using [Stripe Elements Card](https://vuestripe.com/stripe-elements/card/), do you have any example on how to use the elements methods?

I tried to use the `@change` but it is not working.

`<stripe-element-card ref="elementRef" :pk="pulishableKey" @token="tokenCreated" @change="onCardChange" />`

Methods:
`onCardChange(event) {
          console.log(event);
}`

**Comment by chip** [comment]
I would try `@element-change="onCardChange"`

**Comment by jofftiquez** [comment]
> For anyone running into this issue, I would try `@element-change="onCardChange"`. See docs [docs.vuestripe.com/vue-stripe/stripe-elements/card](https://docs.vuestripe.com/vue-stripe/stripe-elements/card)

Thank you for referencing this 💪
