### ISSUE TITLE
Content Security Policy of your site blocks the use of 'eval' in JavaScript`

### ISSUE THREAD

**Issue by weihao** [vue-stripe/vue-stripe#209]
Error Log:
```
The Content Security Policy (CSP) prevents the evaluation of arbitrary strings as JavaScript to make it more difficult for an attacker to inject unathorized code on your site.
To solve this issue, avoid using eval(), new Function(), setTimeout([string], ...) and setInterval([string], ...) for evaluating strings.
```

Source:
https://github.com/vue-stripe/vue-stripe-checkout-nuxt-demo

Reproduce:
https://vue-stripe-checkout-nuxt-demo.web.app/

**Comment by jofftiquez** [comment]
Hello, this may not be relevant to vue-stripe itself as the error/warning is in the demo code. Will close this for now. Thanks.

**Comment by pankgeorg** [comment]
For whoever may end up here, this seems to be relevant to how `vue-stripe` is being bundled:
https://stackoverflow.com/questions/65191809/webpack-babel-functionr-regeneratorruntime-rr-violates-unsafe-eval-cs

Not sure if it is action from this repo's perspective
