### ISSUE TITLE
Insecure host

### ISSUE THREAD

**Issue by ETSVSCode** [vue-stripe/vue-stripe#210]
**Getting this error in local**
Vue Stripe will not work on an insecure host. Make sure that your site is using TCP/SSL.

Also, I am using testing keys.

![image](https://user-images.githubusercontent.com/86507717/124897629-1c087100-dffc-11eb-80a6-edcaf03e82f1.png)

Code :

```
import { StripeElementCard } from "@vue-stripe/vue-stripe";
import { IStripeElementStyle } from "assets@/subscriber/types/checkout";

@Component({
    name: "Checkout",
    components: {
        StripeElementCard,
    },
})
class Checkout extends Mixins(CommonServices) {   
    paymentMethod = "0";
    pulishableKey = process.env.MIX_STRIPE_KEY;
    elementStyle: IStripeElementStyle = {
        base: {
            color: "#32325d",
            fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
            fontSmoothing: "antialiased",
            fontSize: "18px",
            "::placeholder": {
                color: "#aab7c4",
            },
        },
        invalid: {
            color: "red",
            iconColor: "red",
        },
    };
 };
```

**Comment by jofftiquez** [comment]
Hi, may see how your URL in localhost looks like? Thanks.

**Comment by mrdigitalau** [comment]
I second this issue. I set it up originally and it worked without https on test mode but now it doesn't.

I am using laragon and my project is using a domain generated by hosts file http://myproject.test

Is there any way around this?

**Comment by SloS13** [comment]
I'm having this issue as well.  Was working on local a few days ago.

**Comment by jofftiquez** [comment]
Hi all, I understand the problem now. I will add a check to the logic to check if the project is on test mode.

**Comment by Brigat0** [comment]
Same problem here ...

**Comment by benedict-w** [comment]
Any resolution for this?

**Comment by OneLoneFox** [comment]
Same issue as of today

**Comment by pidong** [comment]
Same issue, any fix on this?

**Comment by benedict-w** [comment]
My **hack** so that I could test on an insecure local environment was to find and replace the instances of 'localhost' with my own hostname in the dist files (in the src it's here https://github.com/vue-stripe/vue-stripe/blob/master/src/utils.js#L2). A better solution would probably be to install an SSL locally!

**Comment by Brigat0** [comment]
> My **hack** so that I could test on an insecure local environment was to find and replace the instances of 'localhost' with my own hostname in the dist files (in the src it's here https://github.com/vue-stripe/vue-stripe/blob/master/src/utils.js#L2). A better solution would probably be to install an SSL locally!

Well, thanks for the tips ;)

**Comment by OneLoneFox** [comment]
> My **hack** so that I could test on an insecure local environment was to find and replace the instances of 'localhost' with my own hostname in the dist files (in the src it's here https://github.com/vue-stripe/vue-stripe/blob/master/src/utils.js#L2). A better solution would probably be to install an SSL locally!

Thanks!

Just to elaborate on the issue, I'm using wsl2 to serve my project with `php artisan serve --host=0.0.0.0` for it to be accessible on my host machine I'm then generating a test url with hosts `wsl.test` (not really relevant) so the fix to this issue might need more than checking host names since wsl uses a class b ip and some people use host file URLs. I'd suggest adding a configuration flag instead of checking for the hostname `return this.env === 'local' || window.location.protocol === 'https:';` but that would need the helper function to be a mixin instead.

**Comment by rendom** [comment]
Any update on this?

**Comment by jofftiquez** [comment]
Hello, first of all, apologies for the hiatus. It has been a busy few months for me. I will fix this immediately. The solution I have in mind is to have a `test-mode` boolean props for the component so I can add it as an additional check to bypass the check. Altho it would defeat the purpose of the thing. I'll update you guys. Apologies again.

**Comment by maximemoreillon** [comment]
Sorry to hear about your busy schedule, but are there any news about the test-mode prop?

**Comment by jofftiquez** [comment]
Hello all, apologies for the late action. I added a new prop called `testMode` use this if you want to intentionally bypass the insecure host check. Kindly check the updated docs. Thank you.

**Comment by ChrisClsg** [comment]
> Hello all, apologies for the late action. I added a new prop called `testMode` use this if you want to intentionally bypass the insecure host check. Kindly check the updated docs. Thank you.

Hello @jofftiquez, is there any reason why the `testMode` prop was not also added to the `StripeCheckout` component? 
Using `StripeCheckout` results also in the `Vue Stripe will not work on an insecure host. Make sure that your site is using TCP/SSL.` error as it uses the same `isSecureHost` check that needs to be bypassed.

**Comment by Arturexe** [comment]
@jofftiquez I'm also trying to use the checkout component, which throws the error in a local dev environment. `testMode` would be really useful.
