### ISSUE TITLE
Release dates for other payment methods?

### ISSUE THREAD

**Issue by silveltman** [vue-stripe/vue-stripe#216]
I live in the Netherlands where everyone uses the payment method 'iDeal bank'. The websites says a component for this is coming soon, but is there any indication of when this is exactly?
Thanks!

**Comment by jofftiquez** [comment]
Hello, first of all, apologies for the hiatus, it has been a few busy months for me lately. Thank you for submitting an issue. Payment methods are something that is already on the way. I will look into the timeline again, but this is definitely the next one.

**Comment by sebaqe** [comment]
Hi Jofftiquez! thanks for creating this library and congrats on being an official stripe partner. 
I am trying to figure out if I could use stripe Payment Element (the one that automatically offers multiple payment options based on what the stripe account enables in their dashboard). Is this already available or is it in the plans? I feel like it should probably take precedence over other payment methods, as users could use this and then select from their stripe dashboard what payment methods to enable. 
Please let me know what you think. Also, if this is not available, would it be possible / easy to include stripe payment element into a vuejs SPA without using your library? 
thanks!
Sebastian

**Comment by jofftiquez** [comment]
Hello @silveltman @sebaqe do you think the new Payment Element feature covers your use-case? Let me know. Thanks.

https://docs.vuestripe.com/vue-stripe/stripe-elements/payment

**Comment by silveltman** [comment]
Looks like it would, yeah!
However, I haven't worked with Vue much lately, so will give it a try when I get into another Vue project.

Thanks!

**Comment by jofftiquez** [comment]
Thanks @silveltman I'll be closing this for now. Feel free to open a new issue if you encountered any. Have a great one!
