### ISSUE TITLE
stripe checkout: process is not defined 

### ISSUE THREAD

**Issue by tfnick** [vue-stripe/vue-stripe#220]
## NOTE: Moving forward, issues that does not conform with this format will be closed automatically. (You can delete this part)

**Describe the bug**
I use 'stripe checkout' in my quasar web app, when I access the checkout page in browser, I found some error in console and error info is 'process is not defined'.

I read the vue-stripe code and found content of constant.js as bellow:

export const STRIPE_PARTNER_DETAILS = {
  name: 'vue-stripe',
  version: VUE_STRIPE_VERSION,
  url: process.env.VUE_STRIPE_WEBSITE,
  partner_id: process.env.VUE_STRIPE_PARTNER_ID,
};

if set the vriables VUE_STRIPE_WEBSITE and VUE_STRIPE_PARTNER_ID , the error message disappeared.

I wonder why these two variables are not mentioned in the 'vue stripe checkout' example?

**Comment by tfnick** [comment]
[vue stripe checkout example](https://vuestripe.com/stripe-checkout/recurring-payment)

**Comment by jofftiquez** [comment]
Hello, first of all, apologies for the hiatus. Thank you for submitting an issue. I will look into it immediately. 

The code should not affect your code directly if you exclude vue-stripe for your build process. Anyhow, I will see what I can do.
