### ISSUE TITLE
Shipping rates Vue Stripe Checkout

### ISSUE THREAD

**Issue by Flo2315** [vue-stripe/vue-stripe#222]
**Is your feature request related to a problem? Please describe.**
Unable to add shipping charges in Vue Stripe Checkout

**Describe the solution you'd like**
As for the other props, a new one should be added that allows you to pass the shipping costs id
exemple `shipping-rates="shr_123456789"`

What do you think ?
Thank you 🙏

**Comment by jofftiquez** [comment]
Hello, this is noted. Thank you for submitting an issue. Apologies for the hiatus.

**Comment by sl1der** [comment]
Could definitely use a `shipping-rates: type: Array` prop for the project I'm working on.

**Comment by jofftiquez** [comment]
@Flo2315 @sl1der upon checking there is no such option as `shipping-rates` in the `redirectToCheckout` method. Instead, you can [create a Session](https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-shipping_options-shipping_rate) with the shipping rate option just like you want and [use that session to checkout using Vue Stripe](https://docs.vuestripe.com/vue-stripe/stripe-checkout/sessions).
