### ISSUE TITLE
Allow users to pass in extra data to createToken 

### ISSUE THREAD

**Issue by deidyomega** [vue-stripe/vue-stripe#232]
## NOTE: Moving forward, issues that does not conform with this format will be closed automatically. (You can delete this part)

**Is your feature request related to a problem? Please describe.**
We use stripe radar, and are required to pass in name, and address information to the createToken

**Describe the solution you'd like**
Allow the element to take in extra information as needed.  As shown in this pr:
https://github.com/vue-stripe/vue-stripe/pull/231

**Describe alternatives you've considered**
I forked the code and am doing it on a local copy til your version allows me to pass in the name and address

**Additional context**
I've already done the work here: https://github.com/vue-stripe/vue-stripe/pull/231

**Comment by jofftiquez** [comment]
Merged #231
