### ISSUE TITLE
Warning message for "partner_id" parameter

### ISSUE THREAD

**Issue by tomparle** [vue-stripe/vue-stripe#247]
**Describe the bug**
After upgraded vue-stripe to 4.2.5, when opening my vue app, the following warning is displayed in the developer console :
`Failed to register your library: Invalid value for WrapperLibrary: partner_id should be a string starting with pp_partner_. You specified: .`

**To Reproduce**
1. Create a vue project
2. Add @vue-stripe/vue-stripe 4.2.5
3. Launch the app
4. Display dev console (F12 on Chrome)

**Expected behavior**
There should not be any error/warning message related to Stripe plugin initialization.

**Desktop (please complete the following information):**
 - OS: Linux 
 - Browser : Chrome 96
 - Version : 4.2.5

**Comment by Meas** [comment]
Same thing happening to me. I suppose it is the "stripeAccount" variable that needs to be passed as options, but I'm unsure of what that is suppose to be.

**Comment by opuu** [comment]
I am also getting the same warning.

**Comment by jofftiquez** [comment]
Hi all, I am almost done migrating the docs to GitBook. After that there's just a new feature that I need to implement, then I can go back to the issues. Thank you.

**Comment by craigh411** [comment]
Looks to me like this is coming from here: https://github.com/vue-stripe/vue-stripe/blob/f9151239cd864e2b033a94cbe7cf64775591f54b/src/stripe/index.js#L16

constants.js contains

```
export const STRIPE_PARTNER_DETAILS = {
  name: 'vue-stripe',
  version: VUE_STRIPE_VERSION,
  url: process.env.VUE_STRIPE_WEBSITE || '',
  partner_id: process.env.VUE_STRIPE_PARTNER_ID  || '',
};
```

I would guess that these were local environment variables, which would mean it would work in a development environment where these are set. 

I think that the partner id could just be hardcoded into constants as this id appears to be for helping stripe detect any errors in a plugin.

https://stripe.com/docs/building-plugins#identify-plugin

**Comment by jofftiquez** [comment]
> Looks to me like this is coming from here:
> 
> https://github.com/vue-stripe/vue-stripe/blob/f9151239cd864e2b033a94cbe7cf64775591f54b/src/stripe/index.js#L16
> 
> constants.js contains
> 
> ```
> export const STRIPE_PARTNER_DETAILS = {
>   name: 'vue-stripe',
>   version: VUE_STRIPE_VERSION,
>   url: process.env.VUE_STRIPE_WEBSITE || '',
>   partner_id: process.env.VUE_STRIPE_PARTNER_ID  || '',
> };
> ```
> 
> I would guess that these were local environment variables, which would mean it would work in a development environment where these are set.
> 
> I think that the partner id could just be hardcoded into constants as this id appears to be for helping stripe detect any errors in a plugin.
> 
> https://stripe.com/docs/building-plugins#identify-plugin

Hello @craigh411 you are correct.

**Comment by rpkhatri80s** [comment]
Any Update on this?

**Comment by jofftiquez** [comment]
I will temporarily remove this for now as I cannot remember how to get the value for the stripe partner id, this will just be temporary and I will return this as it is important for Vue Stripe. The next release should fix this.

**Comment by jofftiquez** [comment]
`v4.3.3` should fix this. Thank you. Closing for now. Kindly re-open if still persisting.
