### ISSUE TITLE
redirectToCheckout doesn't return promise from SDK

### ISSUE THREAD

**Issue by Mihailoff** [vue-stripe/vue-stripe#249]
**Describe the bug**
https://stripe.com/docs/js/checkout/redirect_to_checkout

> This method returns a Promise which resolves with a result object. If this method fails, the result object will contain a localized error message in the error.message field.

**To Reproduce**
https://vuestripe.com/stripe-checkout/sessions

**Expected behavior**
Return promise or handle error https://github.com/vue-stripe/vue-stripe/blob/v4.2.9/src/checkout/index.js#L33

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any
 - vue-stripe v4.2.9

**Smartphone (please complete the following information):**
N/A

**Additional context**
In my dev environment `redirectToCheckout()` function silently fails. By using Stripe SDK I managed to get the error

`{ code: "redirect_error", message: "Failed to redirect to https://checkout.stripe.com/pay/zzzzzz" }`

**Comment by jofftiquez** [comment]
Thanks for this, the next version will include this. I kinda missed this one, thank you for pointing out.
