### ISSUE TITLE
Stripe donation support?

### ISSUE THREAD

**Issue by shidcordero** [vue-stripe/vue-stripe#250]
**Is your feature request related to a problem? Please describe.**
How to use this library for a Stripe donation feature?

**Describe the solution you'd like**
-

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by jofftiquez** [comment]
There's a prop to the checkout component called `submitType`.

Stripe docs: https://stripe.com/docs/js/checkout/redirect_to_checkout#stripe_checkout_redirect_to_checkout-options-submitType
VueStripe docs: https://docs.vuestripe.com/vue-stripe/stripe-checkout/getting-started
