### ISSUE TITLE
Setup project with typescript in another branch

### ISSUE THREAD

**Issue by jofftiquez** [vue-stripe/vue-stripe#259]

**Comment by ravikiranr26** [comment]
Hello @jofftiquez Can i get to know more about this task ? Would like to setup and contribute to this task

**Comment by jofftiquez** [comment]
@ravikiranr26 I will deploy the branch for vue3 version soon. I'll let you know here when it's available so you can check it and mess around with it. Thanks!

**Comment by ravikiranr26** [comment]
@jofftiquez Thanks. I started to convert the current vue2 version to typescript and its in progress. on my frok with branch rknmit/with-typescript

**Comment by lespinosa** [comment]
any news about vue3 support.

**Comment by arturosanz** [comment]
Vue 3 ???

**Comment by james090500** [comment]
Mostly working Vue3 build here #308
