### ISSUE TITLE
Type in Payment Elements Demo Example

### ISSUE THREAD

**Issue by escully27** [vue-stripe/vue-stripe#264]
missing an 's' in elementOptions (line 6) and then line 22.

sorry if nit-picky but I think it'll help at least one person in future!

![Screen Shot 2022-01-18 at 10 13 42 PM](https://user-images.githubusercontent.com/11113163/150068488-ea858456-56c8-43fc-96ee-1ab1f2945dcf.png)

**Comment by SecureSnowball** [comment]
Oh man, I can't believe I have wasted an hour trying to figure out what is wrong

**Comment by jofftiquez** [comment]
This has been fixed. Apologies for the mistake.

https://docs.vuestripe.com/vue-stripe/stripe-elements/payment
