### ISSUE TITLE
Don't redirect after successful payment using <stripe-element-payment>

### ISSUE THREAD

**Issue by AbrahamBrookes** [vue-stripe/vue-stripe#269]
**Is your feature request related to a problem? Please describe.**
I am using the `<stripe-element-payment>` component in order to set up a payment intent and allow future payments without having to re-ask for credit card details. I can pass in `confirmParams.return_url` in order to redirect the page on a successful payment, however I don't want to redirect - I want to process the successful payment in-place.

**Describe the solution you'd like**
I'm not sure how it would look but I guess an event on the component when a payment succeeds with relevant details so I can send them to my server instead of redirecting (and reloading the app)

**Describe alternatives you've considered**
I guess I could give up on using payment intents and just have the user enter their card details every time but that's not attractive... Or I could redirect to a script-only page and run some php using url parameters sent from stripe to confirm the payment on my server, the old-school way, but that also requires a full app refresh and breaks the user flow. Or maybe I can prevent the redirect and capture the URL parameters with some sneaky sniffing but I don't know if that's even possible...

**Comment by jofftiquez** [comment]
@AbrahamBrookes I understand, let's see what we can do. 

@yizhuang-chew Are you referring to [this](https://stripe.com/docs/js/payment_intents/confirm_payment#confirm_payment_intent-options-redirect)? If so I believe a `confirmParams` property already exists in the `StripeElementPayment` component. 

Refer to: 
https://github.com/vue-stripe/vue-stripe/blob/d7c86ad0fec644dd6383aa8fda9f5c5109175ae5/src/elements/Payment.vue#L43

Which is being used here:
https://github.com/vue-stripe/vue-stripe/blob/d7c86ad0fec644dd6383aa8fda9f5c5109175ae5/src/elements/Payment.vue#L128-L131

Also, @AbrahamBrookes, thoughts?

**Comment by AbrahamBrookes** [comment]
As I understand it, the `redirect: 'if_required'` param falls _outside_ of the confirmParams block: 

![image](https://user-images.githubusercontent.com/8340776/156901958-ad0e2661-d633-446a-9c61-97f3fe64389b.png)

Which we don't have access to set via the `Elements` component. So, I guess, another prop on the component?

**Comment by AbrahamBrookes** [comment]
simple PR: https://github.com/vue-stripe/vue-stripe/pull/274

**Comment by jofftiquez** [comment]
@AbrahamBrookes I understand now, my bad. This is great I will merge your PR soon.

**Comment by jofftiquez** [comment]
Closing for #274

**Comment by jofftiquez** [comment]
@AbrahamBrookes @yizhuang-chew kindly check `v4.4.2` Thanks.

**Comment by AbrahamBrookes** [comment]
I have finally come back to this, according to https://stripe.com/docs/js/payment_intents/confirm_payment?type=pii#confirm_payment_intent-options-redirect a non-redirected call to `stripe.confirmPayment()` will resolve with a paymentIntent object. My PR emits that back to the caller:

https://github.com/vue-stripe/vue-stripe/pull/288

**Comment by AbrahamBrookes** [comment]
I just dumped a local version and tested the changes, "works on my machine"
