### ISSUE TITLE
New customer created in each subscription.

### ISSUE THREAD

**Issue by YednapNibas** [vue-stripe/vue-stripe#270]
**Describe the bug**
Even though we provide client reference id it's creating a new customer.

**To Reproduce**
1. Add :client-reference-id="customerID" to the vue-stripe component with mode="subscription"
2. Provide valid customerID
3. Subscribe to any product
4. It'll create a new customer.

**Expected behavior**
No new customer should be created but should be added to the existing customer.

**Desktop (please complete the following information):**
 - Browser [Firefox]
 - Version [98.0b6]

**Additional context**
Vue-stripe version:- 4.4.1

**Comment by jofftiquez** [comment]
This is similar to #230 you can read it and the discussion might help you.

**Comment by jofftiquez** [comment]
Closing in favor of #230
