### ISSUE TITLE
Partner page link is broken

### ISSUE THREAD

**Issue by BigBlueHat** [vue-stripe/vue-stripe#278]
**Describe the bug**
The "visit partner" link at https://stripe.com/partners/directory/vue-stripe goes to `vustripe.com` rather than `vuestripe.com`.

**To Reproduce**
1. Go to https://stripe.com/partners/directory/vue-stripe
2. Click on "visit partner"

**Expected behavior**
To end up at vuestripe.com

**Desktop (please complete the following information):**
 - OS: any
 - Browser: all
 - Version: every

**Smartphone (please complete the following information):**
 - Device: any
 - OS: all
 - Browser: every
 - Version: any

**Comment by BigBlueHat** [comment]
Also the top two links at vuestripe.com 404.

**Comment by jofftiquez** [comment]
Thanks @BigBlueHat I messed this one up I will update it immediately thanks.
