### ISSUE TITLE
U

### ISSUE THREAD

**Issue by Damilola365** [vue-stripe/vue-stripe#333]
https://www.ilotbet.com/login/oauth/authorize?redirect_uri=github%3A%2F%2Fcom.github.android%2Foauth&client_id=3f8b8834a91f0caad392&response_type=code&state=OuuOnaP_djBsqGqnsKboFQ&nonce=Vgp8RpC83gLfx3SaZkqDpg&scope=user%20repo%20notifications%20admin%3Aorg%20read%3Adiscussion%20user%3Aassets%20project%20workflow&code_challenge=mRMs3-6pkGZHmxYt1m-gZrUlHpmPJnICDNJgkYknsw8&code_challenge_method=S256&allow_signup=false

**Comment by Yasheikh111** [comment]
https://www.ilotbet.com/login/oauth/authorize?redirect_uri=github%3A%2F%2Fcom.github.android%2Foauth&client_id=3f8b8834a91f0caad392&response_type=code&state=OuuOnaP_djBsqGqnsKboFQ&nonce=Vgp8RpC83gLfx3SaZkqDpg&scope=user%20repo%20notifications%20admin%3Aorg%20read%3Adiscussion%20user%3Aassets%20project%20workflow&code_challenge=mRMs3-6pkGZHmxYt1m-gZrUlHpmPJnICDNJgkYknsw8&code_challenge_method=S256&allow_signup=false
